### ISSUE TITLE
iPhone 11 ios 13.5 Locked up after post-install respring

### ISSUE THREAD

**Issue by tdauria1** [tomaszpoliszuk/ActivatorHapticFeedbackListener#1]
I'm currently backing up phone just in case.. What details can I provide to help diagnose?

As stated, I installed this tweak through cydia (it also installed activator and ~~something else~~ flipswitch at the same time). 
Nothing on the output looked like it failed.
Clicked respring from cydia when prompted.
Lockscreen loaded wallpaper and time then froze.
     Complications widget did not load
     Battery, carrier, cell signal, and wifi icons did not load.
     A bar was loaded like an underscore in top right notch.
Not sure what key combo eventually rebooted it, but was stuck there with no response from buttons or touch for about 5 min. Rejailbreak through unc0ver successful, but rebooted instead of respring and took a while to come back.

When finished backing up will hopefully be able to use unc0ver without loading tweaks and report back with any requested info.

**Comment by tdauria1** [comment]
Update- I did the following:
rejailbreak with unc0ver disabling tweaks
uninstall activatorhapticfeedbacklistener
rejailbreak enabling tweaks

->reboots into unjailbroken state after a few minutes

rejailbreak without tweaks
uninstall activator and flipswitch
rejailbreak with tweaks

->reboots quickly into jailbroken state

Perhaps this is actually an issue with Activator and/or Flipswitch?
Let me know if there are logfiles or something I can retrieve that may be helpful

**Comment by tomaszpoliszuk** [comment]
Could you disable every tweak (for example using iCleaner) and enable only:
- Activator
- Activator Haptic Feedback Listener (this extension for Activator)
- Flipswitch
- PreferenceLoader
- RocketBootstrap

and test if it's working then?

**Comment by tdauria1** [comment]
Sorry I missed the notification for this. It appears to be an activator/flipswitch issue. I can't get activator installed on A13 without causing the above issue. Activator is currently unsupported on A12/A13 so not an issue with your tweak

**Comment by tomaszpoliszuk** [comment]
FYI Activator version 1.9.13 is compatible with A12/A13 - I encourage you to test it a little bit more :)
Have a nice day!
